### ISSUE TITLE
Problem with running test case

### ISSUE THREAD

**Issue by luchua-bc** [github/vscode-codeql-starter#26]
I'm using the CodeQL starter in VS Code to write new queries and it works great for me. The only issue is that I cannot run custom test cases.

First issue I got is the compliant of Java version. In vscode-codeql-starter/ql/java/ql/test/query-tests/maven-dependencies/my-project/.settings/org.eclipse.jdt.core.prefs, it has:
```
eclipse.preferences.version=1
org.eclipse.jdt.core.compiler.codegen.targetPlatform=1.5
org.eclipse.jdt.core.compiler.compliance=1.5
org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures=disabled
org.eclipse.jdt.core.compiler.problem.forbiddenReference=warning
org.eclipse.jdt.core.compiler.problem.reportPreviewFeatures=ignore
org.eclipse.jdt.core.compiler.processAnnotations=disabled
org.eclipse.jdt.core.compiler.release=disabled
org.eclipse.jdt.core.compiler.source=1.5
```
I changed all 3 occurrences of 1.5 to 1.8 since 1.5 is too old and I'm using JDK 1.8. Then the error was gone.

However, after I created a new test then ran the test, I got:
```
The container 'Maven Dependencies' references non existing library '/<user-home>/.m2/repository/com/semmle/another-project/1.0/another-project-1.0.jar'
``` 

There is no directory "/.m2/repository/com/semmle/" created so I guess some dependencies are missing. 

Would you please help? Thanks a lot.

**Comment by luchua-bc** [comment]
I tried to simplify the case by moving both the query and the test case to the same sub-directory under codeql-custom-queries-java. 

Then under the same folder, when I run:
```
codeql test run --search-path=java <sub-directory>
```
I got the following error:
```
ERROR: Dependency not found: codeql-java (vscode-codeql-starter/codeql-custom-queries-java/qlpack.yml:1,1-1)
```

While the qlpack.xml file has the default content:
```
name: codeql-custom-queries-java
version: 0.0.0
libraryPathDependencies: codeql-java
```

I think this approach is closer to get it working. How could I get the codeql-java dependency resolved in the  codeql-custom-queries-java directory? 

Thanks.

**Comment by hmakholm** [comment]
The failure to find `codeql-java` must be because `--search-path=java` defines a search path that doesn't include the `ql` submodule of the starter repo (which is where the usual CodeQL libraries are located).

It is not entirely clear what you were trying to achieve with `--search-path=java`. My guess is that in your earlier experiments your current directory has been the `ql` submodule itself, in which case `java` could have worked.

Try with `--search-path=/full/path/to/vscode-codeql-starter/ql`. If that works better you could consider defining that option once and for all in the global config file as described at https://help.semmle.com/codeql/codeql-cli/reference/configuration-overview.html

**Comment by luchua-bc** [comment]
Thanks @hmakholm a lot. Now my test cases work with the full path.
